apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kiali-grafana-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.Grafana.host }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-grafana
spec:
  hosts:
  - {{ .Values.Grafana.host }}
  gateways:
  - kiali-grafana-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: grafana
        port:
          number: 3000
