apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "istio-kiali.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
