name: Terraform 0.13.*

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker version
      run: docker version

    - name: Terraform 0.13.0 compatibility
      run: |
        docker run -t --rm -v $(pwd):/app/ -w /app/ hashicorp/terraform:0.13.0 init
        docker run -t --rm -v $(pwd):/app/ -w /app/ hashicorp/terraform:0.13.0 validate
